using System;
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        Guid UserId = Guid.Parse("8e445865-a24d-4543-a6c6-9443d048cdb9");
        string UserName = "System Admin";
        string dateCreated = "DateCreatedUtc"; // Assuming you’ll replace with actual variable in EF seed

        var existingDesignations = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "ABHYUDAYA CO-OPERATIVE BANK"
        };

        string rawDesignations = @"

AIRTEL PAYMENTS BANK
AIRTEL PAYMENTS BANK
ALLAHABAD BANK
ALLAHABAD UP GRAMIN BANK
ALMORA URBAN CO-OPERATIVE BANK LTD.
ANDHRA BANK
ANDHRA PRADESH GRAMEENA VIKAS BANK
ANDHRA PRADESH GRAMIN BANK
ANDHRA PRAGATHI GRAMEENA BANK
APNA SAHAKARI BANK LTD
ARYAVART BANK
ARYAVART GRAMIN BANK
ARYAVART KSHETRIYA GRAMIN BANK
ARYAVART UP GRAMIN BANK
ASHOK SAHAKARI BANK LTD
ASSAM COOPERATIVE APEX BANK
AU SMALL FINANCE BANK
AWADH GRAMIN BANK
AXIS BANK
BANDHAN BANK
BANK OF BARODA
BANK OF INDIA
BANK OF MAHARASHTRA
BAREILLY KSHETRIYA GRAMIN BANK
BARODA EASTERN UP GRAMIN BANK
BARODA RAJSTHAN KSHETRIYA GRAMIN BANK
BARODA UP BANK
BARODA UTTAR PRADESH GRAMIN BANK
BASSEIN CATHOLIC CO-OP BANK LTD
BASTI GRAMEEN BANK
BHAGINI NIVEDITA SAHAKARI BANK LTD PUNE
BHAGIRATH GRAMIN BANK
BHARAT BANK
BHARAT CO-OPERATIVE BANK LTD.
BOMBAY MERCANTILE COOPERATIVE BANK LTD
CANARA BANK
CASH
CENTRAL BANK OF INDIA
CHAITANYA GODAVARI GRAMEENA BANK
CHAMPARAN KSHETRIYA GRAMIN BANK
CHHATTISGARH GRAMIN BANK
CHHATTISHGARH RAJYA GRAMIN BANK
CITI BANK
CITY UNION BANK LIMITED
COASTAL LOCAL AREA BANK LTD
CORPORATION BANK
COSMOS BANK
CSB BANK
DAKSHIN BIHAR GRAMIN BANK
DARUSSALAM BANK
DBS BANK
DCB BANK
DENA BANK
DEUTSCHE BANK
DHANLAKSHMI BANK
DISTRICT CO OPERATIVE BANK LTD
DMK JAOLI BANK
DOMBIVLI NAGARI SAHAKARI BANK LIMITED
EQUITAS SMALL FINANCE BANK LIMITED
ESAF SMALL FINANCE BANK LIMITED
ETAWAH DISTRICT CO-OPERATIVE BANK LTD
FEDERAL BANK
FINCARE SMALL FINANCE BANK
FINO PAYMENTS BANK
GOPINATH PATIL PARSIK JANATA SAHAKARI BANK LTD
GP PARSIK JANATA SAHAKARI BANK LTD
GRAMIN BANK OF ARYAVART
GUJARAT STATE COOPERATIVE BANK
GULSHAN MERCANTILE URBAN CO OPERATIVE BANK
HARYANA GRAMIN BANK
HDFC BANK
HE SHAMRAO VITHAL CO-?OPERATIVE BANK LTD
HIMACHAL PRADESH STATE COOPERATIVE BANK LTD
HSBC
ICICI BANK LTD
IDBI BANK LTD.
IDFC BANK
IDFC FIRST BANK
INDIA POST PAYMENTS BANK
INDIAN BANK
INDIAN OVERSEAS BANK
INDUSLND BANK
J D C C BANK LTD
JALGAON JANTA SAHAKARI BANK LTD
JALGAON PEOPLES CO-OPERATIVE BANK
JAMMU AND KASHMIR BANK LIMITED
JAMSHEDPUR URBAN CO-OPERATIVE BANK LTD
JANAKALYAN SAHAKRI BANK LTD
JANASEVA SAHAKARI BANK (BORIVLI) LTD
JANTA SAHAKARI BANK LTD
JHARKHAND RAJYA GRAMIN BANK
JHARKHAND STATE COOPERATIVE BANK
KANGRA CENTRAL COOPERATIVE BANK
KANPUR KSHETRIYA GRAMIN BANK
KARNATAKA BANK
KARNATAKA GRAMIN BANK
KARNATAKA VIKASH GRAMEEN BANK
KARUR VYSYA BANK
KASHI GOMTI SAMYUT GRAMIN BANK
KAVERI GRAMEENA BANK
KERALA GRAMIN BANK
KHAMGAON URBAN CO-OP BANK LTD
KOTAK MAHINDRA BANK
KSHETRIYA GRAMIN BANK
LAKSHMI VILAS BANK
LONAVALA SAHAKARI BANK LTD
LUCKNOW KSHETRIYA GRAMIN BANK
MADHYA BIHAR GRAMIN BANK
MAHARASHTRA GRAMIN BANK
MANSAROVAR URBAN COOPRATIVE BANK LIMITED
NAGAR VIKAS SAHKARI BANK LTD
NAINITAL BANK
NAINITAL DISTRICT COOPERATIVE BANK
NARMADA JHABUA GRAMIN BANK
NATIONAL SECURITIES DEPOSITORY LIMITED
NAVANAGARA URBAN COOP BANK LTD
NEW DELHI - ORIENTAL BANK OF COMMERCE -
NEW INDIA CO-OPERATIVE BANK LTD.
NKGSB CO-OP BANK LTD.
NONE
ODISHA GRAMYA BANK
ORIENTAL BANK OF COMMERCE
PALLAVAN GRAMA BANK
PARSIK SAHAKARI BANK LTD
PATLIPUTRA CENTRAL CO-OPERATIVE BANK
PAYMENTS BANK
PAYTM BANK
PITHORAGARH JILA SAHKARI BANK
PRAGATHI KRISHNA GRAMIN BANK
PRATHAMA UP GRAMIN BANK
PRATHMA BANK
PRERANA CO OPERATIVE BANK LTD
PUNE CANTOMENT SAHAKARI BANK LTD.
PUNE DISTRICT CENTRAL CO-OP BANK
PUNJAB AND SINDH BANK
PUNJAB GRAMIN BANK
PUNJAB NATIONAL BANK
PURVANCHAL GRAMIN BANK
RAEBARELI KSHETRIYA GRAMIN BANK
RAJASTHAN MARUDHARA GRAMIN BANK
RAJDHANI NAGAR SAHKARI BANK LTD
RBL BANK
SAHKARI BANK
SAPTAGIRI GRAMEENA BANK
SARASWAT BANK
SARVA HARAYANA GRAMIN BANK
SARVA UP GRAMIN BANK
SARYU GRAMIN BANK
SHAHJAHANPUR KSHETRIYA GRAMIN BANK
SHARAD NAGARI SAHAKARI BANK LTD
SHINHAN BANK
SOUTH INDIAN BANK
STANDARD CHARTERED BANK
STATE BANK OF BIKANER &amp; JAIPUR
STATE BANK OF HYDERABAD
STATE BANK OF INDIA
STATE BANK OF MYSORE
STATE BANK OF PATIALA
STATE BANK OF TRAVANCORE
STERLING URBAN COOPERATIVE BANK LTD
SUCO BANK
SURYODAY SMALL FINANCE BANK LTD
SVC CO-OPERATIVE BANK LTD.
SYNDICATE BANK
TAMIL NADU GRAMA BANK
TAMILNAD MERCANTILE BANK LTD
TEHRI GARHWAL ZILA SAHKARI BANK LTD
TELANGANA GRAMEENA BANK
TELANGANA STATE CO-OPERATIVE APEX BANK LTD
THE ANDHRA PRADESH STATE COOP BANK LTD
THE ANDHRA PRADESH STATE COOP BANK LTD
THE BUNDI CENTRAL CO-OPERATIVE BANK LTD
THE COSMOS CO-OPERATIVE BANK
THE DECCAN MERCHANTS CO-OPERATIVE BANK LTD
THE DELHI STATE COOPERATIVE BANK LTD.
THE FEDERAL BANK
THE GAYATRI COOPERATIVE URBAN BANK LTD
THE HINDUSTAN CO-OPERATIVE BANK
THE HUBALI URBAN COOPERATIVE BANK
THE JALGAON DISTRICT CENTRAL CO-OPERATIVE BANK
THE JALGAON PEOPLES CO-OPERATIVE BANK LTD.
THE JAMMU &amp; KASHMIR BANK
THE KALYAN JANATA SAHAKARI BANK LTD
THE KANAKAMAHALAKSHMI CO-OPERATIVE BANK LTD
THE KANGRA CENTRAL CO-OPERATIVE BANK LTD
THE KARUR VYSYA BANK LIMITED
THE KURMANCHAL NAGR SAHKARI BANK LTD.
THE LAKSHMI VILAS BANK LTD
THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMIT
THE NAINITAL BANK LTD
THE NASIK MERCHANTS CO-OP BANK LTD
THE NATIONAL BANK
THE NAWANAGAR CO-OPERATIVE BANK LTD
THE RATNAKAR BANK LTD
THE SARASWAT CO-OPERATIVE BANK LTD
THE SATARA SAHAKARI BANK LTD
THE SHAMRAO VITHAL CO-OPERATIVE BANK LTD
THE TAMILNADU STATE APEX COOPERATIVE BANK LIMITED
THE THANE BHARAT SAHAKARI BANK LIMITED
THE THANE DISTRICT CENTRAL CO. OP. BANK LTD
THE VISAKHAPATNAM CO-OP BANK LTD
THE WEST BENGAL STATE COOPERATIVE BANK LTD
TJSB SAHAKARI BANK LTD
TJSB SAHAKARI BANK LTD
TJSB SAHAKARI BANK LTD
UCO BANK
UJJIVAN SMALL FINANCE BANK
UJJIVAN SMALL FINANCE BANK LTD.
UNION BANK OF INDIA
UNITED BANK OF INDIA
URBAN CO-OPERATIVE BANK LTD
URBAN CO-OPERATIVE BANK LTD. BAREILLY
UTKAL GRAMYA BANK
UTKARSH SMALL FINANCE BANK
UTTAR BANGA KHETRIYA GRAMIN BANK
UTTAR BIHAR GRAMIN BANK
UTTAR PRADESH COOPERATIVE BANK
UTTAR PRADESH GRAMIN BANK
UTTARAKHAND GRAMIN BANK
UTTARAKHAND STATE CO-OPERATIVE BANK LTD
UTTARANCHAL GRAMIN BANK
VASAI VIKAS SAHAKARI BANK LTD
VIDHARBHA KONKAN GRAMIN BANK
VIJAYA BANK
YES BANK
ZILA SAHKARI BANK
"; // Add your full list here

        var lines = rawDesignations.Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries);
        int displayOrder = 2;

        foreach (var rawName in lines)
        {
            string name = rawName.Trim();

            if (string.IsNullOrWhiteSpace(name) || existingDesignations.Contains(name))
                continue;

            string guid = Guid.NewGuid().ToString().ToUpper();

            Console.WriteLine(
                $"new Bank {{ Id = Guid.Parse(\"{guid}\"), DisplayOrder = {displayOrder++}, Code = \"{name}\", Name = \"{name}\", " +
                $"DateCreated = {dateCreated}, DateModified = {dateCreated}, " +
                $"CreatedByUserId = UserId, ModifiedByUserId = UserId, " +
                $"CreatedByUserName = UserName, ModifiedByUserName = UserName }},");
        }
    }
}

