using MC.Domain.Entity.Navigation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MC.Persistence.Configurations.Navigation
{
    public class NavigationNodeConfiguration : IEntityTypeConfiguration<MC.Domain.Entity.Navigation.NavigationNode>
    {
        public void Configure(EntityTypeBuilder<MC.Domain.Entity.Navigation.NavigationNode> builder)
        {
            builder.ConfigureAuditFields();

            builder.Property(z => z.Title).HasMaxLength(100);
            builder.Property(z => z.Url).HasMaxLength(256);
            builder.Property(z => z.IconUrl).HasMaxLength(100);

            // Self-referencing relationship (tree)
            builder
                .HasOne(n => n.Parent)
                .WithMany(n => n.Children)
                .HasForeignKey(n => n.ParentId)
                .OnDelete(DeleteBehavior.Restrict);

            Guid UserId = Guid.Parse("8e445865-a24d-4543-a6c6-9443d048cdb9");
            DateTime DateCreatedUtc = new DateTime(2025, 8, 1, 0, 0, 0, DateTimeKind.Utc);
            var userName = "System Admin";

            builder.HasData(
            new NavigationNode
            {
                Id = Guid.Parse("{359B62B8-F29C-423D-BBA2-78C164C7762C}"),
                Title = "Dashboard",
                Url = "/admin/dashboard",
                IconUrl = "",
                DisplayOrder = 1,
                ParentId = null,
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{E591F87A-535E-430E-A38F-20C2228BAB3F}"),
                Title = "Master Data",
                Url = "#",
                IconUrl = "",
                DisplayOrder = 2,
                ParentId = null,
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{A394A640-1C19-4949-9795-5321E7E55C90}"),
                Title = "General",
                Url = "#",
                IconUrl = "",
                DisplayOrder = 1,
                ParentId = Guid.Parse("{E591F87A-535E-430E-A38F-20C2228BAB3F}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{83277279-1AE9-49E5-96F6-579E53918CCA}"),
                Title = "Caste Categories",
                Url = "/admin/caste-categories",
                IconUrl = "",
                DisplayOrder = 1,
                ParentId = Guid.Parse("{A394A640-1C19-4949-9795-5321E7E55C90}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{984FB724-F924-40C8-B667-753ABD515A49}"),
                Title = "Countries",
                Url = "/admin/countries",
                IconUrl = "",
                DisplayOrder = 2,
                ParentId = Guid.Parse("A394A640-1C19-4949-9795-5321E7E55C90"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{A51AA7B3-CC4A-4191-A061-8CECE9C11A75}"),
                Title = "Genders",
                Url = "/admin/genders",
                IconUrl = "",
                DisplayOrder = 3,
                ParentId = Guid.Parse("A394A640-1C19-4949-9795-5321E7E55C90"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{E49F315D-4ED0-4002-80AD-D81001FE0D1A}"),
                Title = "Highest Educations",
                Url = "/admin/highest-educations",
                IconUrl = "",
                DisplayOrder = 4,
                ParentId = Guid.Parse("A394A640-1C19-4949-9795-5321E7E55C90"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{75D38D82-7F26-488E-8BD9-0EAEA1B08633}"),
                Title = "Religions",
                Url = "/admin/religions",
                IconUrl = "",
                DisplayOrder = 5,
                ParentId = Guid.Parse("A394A640-1C19-4949-9795-5321E7E55C90"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{B73A59F0-CDD5-4895-A0E7-FEEA45FF5511}"),
                Title = "Titles",
                Url = "/admin/titles",
                IconUrl = "",
                DisplayOrder = 6,
                ParentId = Guid.Parse("A394A640-1C19-4949-9795-5321E7E55C90"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{57EC63E1-52D5-44CC-A9D1-CDED389F2014}"),
                Title = "Zipcodes",
                Url = "/admin/zipcodes",
                IconUrl = "",
                DisplayOrder = 7,
                ParentId = Guid.Parse("A394A640-1C19-4949-9795-5321E7E55C90"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                Title = "Company",
                Url = "#",
                IconUrl = "",
                DisplayOrder = 2,
                ParentId = Guid.Parse("{E591F87A-535E-430E-A38F-20C2228BAB3F}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{D7C6B998-C97E-4235-8E9E-E3661AA6753D}"),
                Title = "Assets",
                Url = "/admin/assets",
                IconUrl = "",
                DisplayOrder = 1,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{12A135F3-D536-4250-ACBF-A38AAD2D802A}"),
                Title = "Banks",
                Url = "/admin/banks",
                IconUrl = "",
                DisplayOrder = 2,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{5A770876-0D03-4841-BFE0-7C56D4B561D2}"),
                Title = "Branchs",
                Url = "/admin/branch",
                IconUrl = "",
                DisplayOrder = 3,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{C5571635-29DC-4196-9091-A866C1DA3BC4}"),
                Title = "Categories",
                Url = "/admin/categories",
                IconUrl = "",
                DisplayOrder = 4,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{FC58CB5D-D393-4D89-B0FE-7BCB1B013061}"),
                Title = "Designations",
                Url = "/admin/designations",
                IconUrl = "",
                DisplayOrder = 5,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{028F48A9-A50D-495A-A27E-39C84DA74B9A}"),
                Title = "Document Types",
                Url = "/admin/document-types",
                IconUrl = "",
                DisplayOrder = 6,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{734DB850-8030-4F9E-8A14-20AE10AE8CB3}"),
                Title = "Recruitment Types",
                Url = "/admin/recruitment-types",
                IconUrl = "",
                DisplayOrder = 7,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{4D156919-C672-43DF-AA19-D93E975D5BDA}"),
                Title = "Menu",
                Url = "/admin/navigation-nodes",
                IconUrl = "",
                DisplayOrder = 8,
                ParentId = Guid.Parse("{4956B6A2-DD9D-4D7D-85BB-6961076C4F13}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{F80AB6D3-DADF-45E9-81AD-462679804C33}"),
                Title = "Staff Profiles",
                Url = "/admin/staff-profiles",
                IconUrl = "",
                DisplayOrder = 3,
                ParentId = null,
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{C414E1D3-C63C-4EAF-AF0D-EAB721CCC5A5}"),
                Title = "Registeration",
                Url = "/admin/register",
                IconUrl = "",
                DisplayOrder = 4,
                ParentId = null,
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{3F484034-AFC6-4853-A76C-C064B34C2C84}"),
                Title = "Organizations",
                Url = "#",
                IconUrl = "",
                DisplayOrder = 5,
                ParentId = null,
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{358AA86A-FC2E-4BB5-80B5-2A29892E8432}"),
                Title = "Companies",
                Url = "/admin/companies",
                IconUrl = "",
                DisplayOrder = 1,
                ParentId = Guid.Parse("{3F484034-AFC6-4853-A76C-C064B34C2C84}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{E32C3111-85B2-46C7-B2C8-3F65C1F0ADEB}"),
                Title = "Client Masters",
                Url = "/admin/client-masters",
                IconUrl = "",
                DisplayOrder = 2,
                ParentId = Guid.Parse("{3F484034-AFC6-4853-A76C-C064B34C2C84}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{F0002561-462E-4767-8F5E-08BFD53F42F0}"),
                Title = "Client Units",
                Url = "/admin/client-units",
                IconUrl = "",
                DisplayOrder = 3,
                ParentId = Guid.Parse("{3F484034-AFC6-4853-A76C-C064B34C2C84}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{5C8F1888-76E1-4dE2-B848-E2DD181CC2F4}"),
                Title = "Approval",
                Url = "#",
                IconUrl = "",
                DisplayOrder = 6,
                ParentId = null,
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{E19C5A99-DC2C-4E23-8F73-71C79C2966F7}"),
                Title = "Approval Workflows",
                Url = "/admin/approval-workflows",
                IconUrl = "",
                DisplayOrder = 1,
                ParentId = Guid.Parse("{5C8F1888-76E1-4dE2-B848-E2DD181CC2F4}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{8D9A9DDf-B3C3-4E95-B76E-A6BA646D0C01}"),
                Title = "Approval Stages",
                Url = "/admin/approval-stages",
                IconUrl = "",
                DisplayOrder = 2,
                ParentId = Guid.Parse("{5C8F1888-76E1-4dE2-B848-E2DD181CC2F4}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{CA0BB9E6-EE53-4143-9EDB-7CE118804B5B}"),
                Title = "Approval Stage Approvers",
                Url = "/admin/approval-stage-approvers",
                IconUrl = "",
                DisplayOrder = 3,
                ParentId = Guid.Parse("{5C8F1888-76E1-4dE2-B848-E2DD181CC2F4}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{BF88A20B-F140-4B74-8E87-C4A1B39F3A7F}"),
                Title = "Reports",
                Url = "#",
                IconUrl = "",
                DisplayOrder = 7,
                ParentId = null,
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            },
            new NavigationNode
            {
                Id = Guid.Parse("{50396E86-CB2E-4884-BEA0-E9083E205E4B}"),
                Title = "Staff Reports",
                Url = "/admin/staff-reports",
                IconUrl = "",
                DisplayOrder = 1,
                ParentId = Guid.Parse("{BF88A20B-F140-4B74-8E87-C4A1B39F3A7F}"),
                IsActive = true,
                DateCreated = DateCreatedUtc,
                DateModified = DateCreatedUtc,
                CreatedByUserId = UserId,
                ModifiedByUserId = UserId,
                CreatedByUserName = userName,
                ModifiedByUserName = userName,
            }
        );


        }
    }
}
